TecnoballZ AGA
TecnoballZ-AA-1.png,TecnoballZ-AA-2.png,TecnoballZ-AA-3.png,TecnoballZ-AA-4.png,TecnoballZ-AA-5.png,TecnoballZ-AA-6.png,TecnoballZ-AA-7.png
TecnoballZ AGA est sorti fin avril 1995
TecnoballZ <abbr title="Advanced Graphics Amiga" lang="en">AGA</abbr> est une adaptation de TecnoballZ pour l'Amiga&nbsp;1200. Le jeu a été adapté pour tirer parti du microprocesseur Motorola 68020 et des nouvelles puces graphiques <abbr title="Advanced Graphics Amiga" lang="en">AGA</abbr>.
Le jeu nécessite donc un Amiga&nbsp;1200 <abbr title="Advanced Graphics Amiga" lang="en">AGA</abbr> avec 2&nbsp;<abbr title="mégaoctet">Mo</abbr> de <abbr title="Random Access Memory" lang="en">RAM</abbr>. Le jeu a été développé sous l'assembleur Devpac&nbsp;3.
Ce ludiciel tient sur une seule disquette AMIGA <acronym title="Old File System">OFS</acronym> et est téléchargable au format <abbr title="Amiga Disk File" lang="en">ADF</abbr>.
Cette version apporte quelques petites optimisations notables&nbsp;: utilisation des instructions 68020, des sprites de 64 pixels de large, de la palette 16 millions (au lieu de 4096 couleurs), de la mémoire supplémentaire (les Amiga&nbsp;1200 sont équipés de 2&nbsp;<abbr title="mégaoctet">Mo</abbr> de <abbr title="Random Access Memory" lang="en">RAM</abbr>). Le jeu a emprunté plusieurs options de <a href="/tronic.php">Tronic</a>, et comporte beaucoup d'autres améliorations.
Les photos d'écran de cette page sont tirées de la version <abbr title="Advanced Graphics Amiga" lang="en">AGA</abbr>, émulée par le logiciel UAE&nbsp;0.8.21 tournant sous Linux Mandrake 9.0.
Une <a href="http://linux.tlk.fr/games/TecnoballZ/" hreflang="en">version <abbr title="GNU General Public License" lang="en">GPL</abbr> de TecnoballZ est aussi disponible sous Linux</a>. Cette version est entièrement réécrite en C/C++. 
<a href="/adf/TecnoballZ_AA.adf"><img src="/gfx/download.gif" alt="icône téléchargement" title="Télécharge TecnoballZ AGA"/></a>Version finale de TecnoballZ <abbr title="Advanced Graphics Amiga" lang="en">AGA</abbr>. Fonctionne parfaitement avec <abbr title="Unix Amiga Emulator" lang="en">UAE</abbr>. (Testée sur Linux Mandrake 9.0, UAE 0.8.21, et le Kickstart 3.1)
