TecnoballZ
TecnoballZ-1.png,TecnoballZ-2.png,TecnoballZ-3.png,TecnoballZ-4.png
TecnoballZ est sorti fin 1991.
TecnoballZ est une refonte de <a href="{jurl 'amigatlk~games:view@classic', array( 'name' => 'Tecnoball', 'lang' => $lang ) }">Tecnoball</a>. Les graphismes ont entièrement été refaits en trente-deux couleurs par Jean-Michel Martin de Santero  et le code optimisé par Bruno Ethvignot.
Les niveaux, les musiques et les sons sont ceux de Tecnoball, mais des gardiens intermédiaires ont été rajoutés à mi-parcours de chaque zone.
Le jeu fonctionne toujours avec un <a href="http://fr.wikipedia.org/wiki/Motorola_68000">Motorola 68000</a>, l'<a href="http://fr.wikipedia.org/wiki/Original_Amiga_chipset"><abbr title="Old Chip Set" lang="en">OCS</abbr></a> et 512 <abbr title="kilooctet">Kio</abbr> de <abbr title="Read Only Memory" lang="en">RAM</abbr>, un simple Amiga&nbsp;500 donc. Le jeu a été entièrement réécrit sous l'assembleur Devpac&nbsp;2. C'est sans aucun doute le meilleur jeu développé par <a href="http://www.tlkgames.com/">TLK Games</a> sur cette machine.
Le format de disquette TLK-DOS a rendu difficile la préservation de ce jeu sous fichier. Mais en juillet 2012, Dlfrsilver a réussi à préserver TecnoballZ et Kaffer a le convertir aux formats <abbr title="Amiga Disk File">ADF</abbr> étendu et <abbr title="Interchangeable Preservation Format">IPF</abbr>. Un grand merci à eux deux&nbsp;!
À noter que ce jeu a été porté sous Atari ST et PC-DOS, mais ces versions sont moins réussies que l'original. <a href="http://www.sukria.net/fr/">Alexis Sukrieh</a> propose une <a href="http://www.sukria.net/fr/index.php?m=20040320">petite documentation sur la façon de faire fonctionner TecnoballZ avec l'émulateur Atari ST sous Linux</a>.
Les photos d'écran de cette page sont tirées de la version de démonstration de la version <abbr title="Old Chip Set" lang="en">OCS</abbr>  sur le même fichier <abbr title="Amiga Disk File">ADF</abbr> que celui du jeu <a href="equality.php">Equality</a>.
Une <a href="http://linux.tlk.fr/games/TecnoballZ/" hreflang="en">version <abbr title="GNU General Public License" lang="en">GPL</abbr> de TecnoballZ est aussi disponible sous Linux</a>. Cette version est entièrement réécrite en C/C++. 
<a class="icone" title="Télécharger TecnoballZ OCS" href="/adf/tecnoballz_1992_original_tlk-games-amiga-ocs-512-kib_tlk-dos-mfm-format_adf.zip"><img src="/gfx/download.gif" alt="icône téléchargement"/></a> <a href="/adf/tecnoballz_1992_original_tlk-games-amiga-ocs-512-kib_tlk-dos-mfm-format_adf.zip">Version finale et originale de TecnoballZ</a> convertie de la version disquette TLK-DOS en <abbr title="Amiga Disk File">ADF</abbr> étendu le 26 juillet 2012. Cette version a été testée avec succès sur <cite>Ubuntu Linux 12.04</cite> et <a href="http://fengestad.no/wp/fs-uae">FS-UAE 1.2</a>.
