&nbsp;
<img src="/gfx/amigalogo.gif" alt="Logo Amiga" title=""/><h1>&nbsp;</h1>
<a href="http://fr.wikipedia.org/wiki/Amiga">L'Amiga</a> est un micro-ordinateur apparu dans le milieu des années 80. L'Amiga était très novateur pour son époque.
Ce site met en ligne quelques jeux &laquo;&nbsp;rescapés&nbsp;&raquo; produit par la société <a href="http://www.tlkgames.com/fr/company/about">TLK Games</a> dans le début des années 1990.
<a href="http://www.tlkgames.com/fr/company/about">TLK Games</a> est né en octobre 1990 de la passion de cinq personnes pour l'Amiga. Voir <a href="/casse-tete-alternatif.php" title="Cass-t&ecirc;te alternatif">l'article de Micro News de 1991</a>.
En 1990 nous avions commencé à développer un jeu de course de voitures futuristes appelé &laquo;&nbsp;Mad Race&nbsp;&raquo;, mais le projet fut abandonné.
En 1991 sortait notre premier jeu sur Amiga&nbsp;: <a href="{jurl 'amigatlk~games:view@classic', array( 'name' => 'Tecnoball', 'lang' => $lang )}">Tecnoball</a>. Un casse brique aux multiples options. J'ai retrouvé une version piratée par <a href="http://www.skidrow.dk/" hreflang="en">Skid Row</a> sur le Web disponible en deux fichiers <abbr title="Amiga Disk File">ADF</abbr>.
Puis nous avons commencé un autre jeu, un <a href="http://fr.wikipedia.org/wiki/Jeu_de_puzzle" hreflang="fr">jeu de puzzle</a> nommé Equality, bien que terminé à 90%, Equality ne fut jamais finalisé. Le jeu étant sur un format de disque spécial développé par <a href="http://www.tlkgames.com/fr/company/about">TLK Games</a>, je ne puis malheureusement le convertir au format <abbr title="Amiga Disk File">ADF</abbr>.
Fin 1991 sorti une version bien améliorée de Tecnoball : <a href="{jurl 'amigatlk~games:view@classic', array( 'name' => 'TecnoballZ', 'lang' => $lang )}">TecnoballZ</a>. Ce jeu n'est pas disponible en <abbr title="Amiga Disk File">ADF</abbr> pour les mêmes raisons que Equality. Mais <a href="{jurl 'amigatlk~games:view@classic', array( 'name' => 'TecnoballZ-AGA', 'lang' => $lang )}">une version <acronym title="Advanced Graphics Amiga" lang="en">AGA</acronym></a> fut développée par la suite. Une version Atari-ST et PC-DOS existent également, mais ces deux versions sont beaucoup moins réussies. (<em>A noter également l'existence d'une <a href="http://linux.tlk.fr/games/TecnoballZ/" hreflang="en">version Linux de TecnoballZ</a> sortie fin 2004</em>)
En 1992 sortit une nouvelle version d' <a href="{jurl 'amigatlk~games:view@classic', array( 'name' => 'Equality-92', 'lang' => $lang )}">Equality</a> repensée et plus simple sur PC-DOS. Cette version fut portée par la suite sur Amiga.
Enfin en 1994 sortit <a href="{jurl 'amigatlk~games:view@classic', array( 'name' => 'tronic', 'lang'=> $lang )}">Tronic</a> sur PC-DOS, un nouveau casse-brique, qui fut porté sur Amiga <acronym title="Advanced Graphics Amiga" lang="en">AGA</acronym>, profitant beaucoup des routines de TecnoballZ-<acronym title="Advanced Graphics Amiga" lang="en">AGA</acronym>&nbsp;!
